### PR TITLE
[ Role CMD ] List out all the available public roles

### PR DESCRIPTION
**Pull request by rojen11**

### CODE REVIEW

**Comment by ashiishme** [comment]
@rojen11 There are other commits and file like feature request template in this PR. Is your fork up to date with `main` or `development`?

**Comment by rojen11** [comment]
I got that when I pulled the main branch. It seems like the feature request template is not available in the development branch so it shows that as an added file.

**Comment by ashiishme** [comment]
> I got that when I pulled the main branch. It seems like the feature request template is not available in the development branch so it shows that as an added file.

Yes, it is only available in main branch, did you fetch everything from the upstream & then switch to development before making changes?

**Comment by rojen11** [comment]
I worked on the previous branch and later pulled from the main and development branches.
Do I make a new pull request?

**Comment by ashiishme** [comment]
> I worked on the previous branch and later pulled from the main and development branches.
> Do I make a new pull request?

I am merging this PR but you need to update your fork first and then make changes  before sending PR next time.

**Review by ashiishme — APPROVED** [review]

**Comment by rojen11** [comment]
Sorry for that. I will keep that in mind next time.
Thank you.

**Pull request merged**
